n_particles: 30
seed: 12345
exposed_stage_chage_rate: 0.075
infection_rate: 0.06
# 1.5/70
infectious_stage_chage_rate: 0.02142857142857143
observation_probability: 0.5
E_immigration_rate: 0.0
I_immigration_rate: 0.0
outfilename: particles.Int64.bin
tstep: 1
nsteps: 100
initial_E: 40
initial_I: 0
initial_O: 0