n_particles: 20
seed: 1234567
exposed_stage_chage_rate: 0.375
infection_rate: 0.3
# 1.5/70*5
infectious_stage_chage_rate: 0.10714285714285715
observation_probability: 0.75
E_immigration_rate: 0.0
I_immigration_rate: 0.0
outfilename: particles.Int64.bin
tstep: 1
nsteps: 25
initial_E: 6
initial_I: 0
initial_O: 0